name: Sync Forked Repositories

on:
  push:
    branches:
      - main  # main 브랜치에 push가 발생할 때 실행

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name "ncb6206"
          git config --global user.email "ncb6206@gmail.com"

      - name: Fetch Forked Repo
        run: |
          git remote add forked https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ncb6206/front.git
          git fetch forked main

      - name: Merge Changes from Original Repo
        run: |
          git fetch origin main  # 원본 레포지토리에서 최신 변경 사항 가져오기
          git merge --no-ff origin/main  # 병합 수행

      - name: Push Changes to Forked Repo
        run: |
          git push forked main  # 병합된 결과를 fork 레포지토리에 푸시
