name: Notify Fork to Sync

on:
  push:
    branches:
      - main  # main 브랜치에 push가 발생할 때 실행

jobs:
  notify-fork:
    if: github.repository == 'podofarm-dev/front'  # fork된 레포지토리에서는 실행 안 됨
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook to Forked Repo
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          --data '{"event_type": "sync-upstream"}' \
          https://api.github.com/repos/ncb6206/front/dispatches
